// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVv-ZsQ0HanwZcxgf6Dm7MCSnzNX8c0J0',
    appId: '1:1011020440970:web:c86e54d3e8e3c11d9ad473',
    messagingSenderId: '1011020440970',
    projectId: 'app-salud-7e77d',
    authDomain: 'app-salud-7e77d.firebaseapp.com',
    storageBucket: 'app-salud-7e77d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFg4hlOxPrm4imQrjLVJyMriw42kuytpo',
    appId: '1:1011020440970:android:607575e3ec393d759ad473',
    messagingSenderId: '1011020440970',
    projectId: 'app-salud-7e77d',
    storageBucket: 'app-salud-7e77d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwNFaw9HUDETNsQycjb7a0TQc03obRc8c',
    appId: '1:1011020440970:ios:289470835437d5e49ad473',
    messagingSenderId: '1011020440970',
    projectId: 'app-salud-7e77d',
    storageBucket: 'app-salud-7e77d.firebasestorage.app',
    iosBundleId: 'com.example.tiendaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwNFaw9HUDETNsQycjb7a0TQc03obRc8c',
    appId: '1:1011020440970:ios:289470835437d5e49ad473',
    messagingSenderId: '1011020440970',
    projectId: 'app-salud-7e77d',
    storageBucket: 'app-salud-7e77d.firebasestorage.app',
    iosBundleId: 'com.example.tiendaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVv-ZsQ0HanwZcxgf6Dm7MCSnzNX8c0J0',
    appId: '1:1011020440970:web:65f41c40ce2d8bf19ad473',
    messagingSenderId: '1011020440970',
    projectId: 'app-salud-7e77d',
    authDomain: 'app-salud-7e77d.firebaseapp.com',
    storageBucket: 'app-salud-7e77d.firebasestorage.app',
  );
}
